version: "3.9"

services:
  app:
    build: .
    command: nodemon --watch /usr/src/exam-project -e js app.js
    ports:
      - "3000:3000"
    env_file:
      - ./init/.env
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: docker.io/library/mongo:noble
    volumes:
      - mongo-data:/data/db
      - ./init:/init
    ports:
      - "27017:27017"

volumes:
  mongo-data: