version: "3.9"

services:
  app:
    build: .
    command: nodemon --watch /usr/src/app -e js app.js
    ports:
      - "3000:3000"
    env_file:
      - ./init/.env
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: docker.io/mongo:noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: exam-project
    volumes:
      - mongo-data:/data/db
      - ./init:/docker-entrypoint-initdb.d:ro
    ports:
      - "27017:27017"

volumes:
  mongo-data: